apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: testsecret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: example-secret-store
    kind: SecretStore
  target:
    name: new-secret
  data:
  - secretKey: SUPERSECRET
    remoteRef:
      key: vault/org/namespace/secret1
      version: v1
  - secretKey: MEGASECRET
    remoteRef:
      key: vault/org/namespace/secret2
      version: v1
