apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: example-secret-store
spec:
  provider:
    fake:
      data:
        - key: "vault/org/namespace/secret1"
          value: "Hello automit!"
          version: "v1"
        - key: "vault/org/namespace/secret2"
          value: "Hello automit - YAY!"
          version: "v1"
