image:
  name: traefik
  pullPolicy: IfNotPresent
service:
  type: NodePort
ports:
  web:
    nodePort: 30000
    # port: 80
  websecure:
    nodePort: 30001
    # port: 443
nodeSelector:
  ingress-ready: 'true'
